name: Continus Integration Check
run-name: ${{ github.actor }} Push an Update

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
            php-version: '7.4'

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: composer manifest package validation
        run: composer validate --strict

      - name: install composer dependencies
        run: composer install

      - name: Create Database
        run: |
          touch database/database.sqlite

      - name: Running Migration
        run: php artisan migrate